import React,{useEffect,useRef,useState}from'react';
import{createRoot}from'react-dom/client';
import gsap from'gsap';
import{ScrollTrigger}from'gsap/ScrollTrigger';
import'./styles.css';
gsap.registerPlugin(ScrollTrigger);
const photos=[
'https://images.unsplash.com/photo-1500375592092-40eb2168fd21?auto=format&fit=crop&w=1800&q=82',
'https://images.unsplash.com/photo-1498623116890-37e912163d5d?auto=format&fit=crop&w=1800&q=82',
'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=1800&q=82',
'https://images.unsplash.com/photo-1473116763249-2faaef81ccda?auto=format&fit=crop&w=1800&q=82',
'https://images.unsplash.com/photo-1519225421980-715cb0215aed?auto=format&fit=crop&w=1800&q=82',
'https://images.unsplash.com/photo-1522673607200-164d1b6ce486?auto=format&fit=crop&w=1800&q=82',
'https://images.unsplash.com/photo-1515934751635-c81c6bc9a2d8?auto=format&fit=crop&w=1800&q=82',
'https://images.unsplash.com/photo-1606216794074-735e91aa2c92?auto=format&fit=crop&w=1800&q=82',
'https://images.unsplash.com/photo-1511285560929-80b456fea0bc?auto=format&fit=crop&w=1800&q=82',
'https://images.unsplash.com/photo-1464366400600-7168b8af9bc3?auto=format&fit=crop&w=1800&q=82',
'https://images.unsplash.com/photo-1520854221256-17451cc331bf?auto=format&fit=crop&w=1800&q=82',
'https://images.unsplash.com/photo-1544078751-58fee2d8a03b?auto=format&fit=crop&w=1800&q=82',
'https://images.unsplash.com/photo-1492684223066-81342ee5ff30?auto=format&fit=crop&w=1800&q=82',
'https://images.unsplash.com/photo-1537907510278-a8e2ed8f3f7f?auto=format&fit=crop&w=1800&q=82'
];
const fallback='data:image/svg+xml;charset=UTF-8,'+encodeURIComponent(`<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 1200 1500"><defs><linearGradient id="g" x1="0" y1="0" x2="1" y2="1"><stop stop-color="#0d4e55"/><stop offset=".5" stop-color="#d7eee8"/><stop offset="1" stop-color="#e98970"/></linearGradient></defs><rect width="1200" height="1500" fill="url(#g)"/><circle cx="600" cy="740" r="330" fill="none" stroke="#fff" stroke-opacity=".38" stroke-width="4"/></svg>`);
function Photo({src,alt,className='',eager=false}){return <img className={className} src={src} alt={alt} loading={eager?'eager':'lazy'} fetchPriority={eager?'high':'auto'} onError={e=>{if(e.currentTarget.src!==fallback)e.currentTarget.src=fallback}}/>}
function App(){const root=useRef(null);const[entered,setEntered]=useState(false);useEffect(()=>{if(!entered||matchMedia('(prefers-reduced-motion: reduce)').matches)return;const ctx=gsap.context(()=>{gsap.from('.hero-copy>*',{opacity:0,y:34,stagger:.08,duration:.9,ease:'power3.out'});gsap.to('.hero-photo',{scale:1.08,yPercent:5,ease:'none',scrollTrigger:{trigger:'.hero',start:'top top',end:'bottom top',scrub:1}});gsap.utils.toArray('.reveal').forEach(el=>gsap.from(el,{opacity:0,y:42,duration:.8,scrollTrigger:{trigger:el,start:'top 84%'}}));const port=gsap.timeline({scrollTrigger:{trigger:'.porthole',start:'top top',end:'+=240%',pin:true,scrub:1}});port.to('.porthole-ring',{scale:4.4,rotation:28},0).to('.porthole-a',{scale:1.12},0).fromTo('.porthole-b',{clipPath:'circle(0% at 50% 50%)'},{clipPath:'circle(52% at 50% 50%)'},.5).to('.porthole-copy',{opacity:0,y:-80},.85).fromTo('.porthole-c',{clipPath:'circle(0% at 50% 50%)'},{clipPath:'circle(75% at 50% 50%)'},1.15);const ribbon=gsap.timeline({scrollTrigger:{trigger:'.tide-ribbon-wrap',start:'top top',end:'+=230%',pin:true,scrub:1}});ribbon.to('.tide-ribbon',{x:()=>-(document.querySelector('.tide-ribbon').scrollWidth-innerWidth+innerWidth*.12),rotation:-2,ease:'none'},0).to('.waterline',{scaleX:1,transformOrigin:'left'},0);gsap.from('.wordwave span',{yPercent:115,stagger:.04,duration:1,ease:'power4.out',scrollTrigger:{trigger:'.wordwave',start:'top 74%'}});gsap.to('.tidepool .orb',{y:(i)=>i%2?-28:24,x:(i)=>i%2?16:-14,repeat:-1,yoyo:true,duration:5,stagger:.2,ease:'sine.inOut'});},root);return()=>ctx.revert()},[entered]);return <main ref={root} className={entered?'entered':''}>{!entered&&<section className="arrival"><div className="waterpane"><div className="waterline-enter"/></div><div className="arrival-copy"><p>PROJECT 024 · COASTAL DAWN</p><h1>Tideglass<br/>Vows</h1><button onClick={()=>setEntered(true)}>Let the tide out</button><span>06:12 · salt / glass / first light</span></div></section>}
<section className="hero scene"><Photo src={photos[0]} alt="Ocean at first light" className="hero-photo" eager/><div className="hero-tint"/><div className="hero-copy"><p className="meta">01 · First Light</p><h2>Where the sea<br/><i>kept the promise.</i></h2><p>A coastal dawn story shaped by sea-glass green, salt white, wet sand and one line of coral sunrise.</p><span className="scroll">scroll with the tide ↓</span></div></section>
<section className="horizon scene"><div className="horizon-copy reveal"><p className="meta">02 · Before Anyone Arrived</p><h3>The horizon<br/>was already dressed.</h3><p>Wind in linen. Silver water. Nothing yet asking to become a photograph.</p></div><Photo src={photos[2]} alt="Calm shoreline horizon"/></section>
<section className="porthole scene"><div className="porthole-a layer"><Photo src={photos[4]} alt="Wedding portrait by the sea"/></div><div className="porthole-b layer"><Photo src={photos[5]} alt="Close editorial wedding portrait"/></div><div className="porthole-c layer"><Photo src={photos[6]} alt="Intimate wedding moment"/></div><div className="porthole-ring"/><div className="porthole-copy"><p className="meta">03 · Through the Glass</p><h3>Scroll becomes<br/>a lens.</h3></div></section>
<section className="postcards scene"><div className="postcard-copy reveal"><p className="meta">04 · Salt Notes</p><h3>Three things<br/>the morning kept.</h3></div><article className="card c1"><Photo src={photos[7]} alt="Wedding detail"/><span>linen / 06:31</span></article><article className="card c2"><Photo src={photos[8]} alt="Couple portrait"/><span>hands / 06:44</span></article><article className="card c3"><Photo src={photos[9]} alt="Floral celebration detail"/><span>flowers / 06:52</span></article></section>
<section className="tide-ribbon-wrap scene"><header><p className="meta">05 · The Tide Ribbon</p><span>one continuous morning / four interruptions</span></header><div className="waterline"/><div className="tide-ribbon"><figure><Photo src={photos[4]} alt="Coastal wedding portrait"/><figcaption>portrait</figcaption></figure><figure className="low"><Photo src={photos[10]} alt="Wedding candid"/><figcaption>breath</figcaption></figure><figure><Photo src={photos[7]} alt="Wedding couple close portrait"/><figcaption>promise</figcaption></figure><figure className="wide"><Photo src={photos[12]} alt="Celebration scene"/><figcaption>arrival</figcaption></figure><figure><Photo src={photos[11]} alt="Quiet portrait"/><figcaption>after</figcaption></figure></div></section>
<section className="quiet scene"><p className="meta">06 · Low Tide</p><blockquote className="reveal">Some moments need<br/><em>more shore around them.</em></blockquote></section>
<section className="tidepool scene"><div className="tidepool-copy reveal"><p className="meta">07 · Tide Pool</p><h3>Details float<br/>before they settle.</h3></div><div className="orb o1"><Photo src={photos[9]} alt="Wedding floral detail"/></div><div className="orb o2"><Photo src={photos[6]} alt="Wedding hands detail"/></div><div className="orb o3"><Photo src={photos[11]} alt="Editorial wedding portrait"/></div></section>
<section className="shoreline scene"><Photo src={photos[3]} alt="Coastal landscape"/><div className="shoreline-copy reveal"><p className="meta">08 · Ceremony Line</p><h3>Stand here.<br/>Face the water.<br/>Forget the camera.</h3></div></section>
<section className="contact scene"><div className="contact-copy reveal"><p className="meta">09 · Everyone Else</p><h3>The morning widens.</h3></div>{[12,7,8,10].map((i,n)=><Photo key={n} src={photos[i]} alt="Celebration candid" className={`ct ct${n+1}`}/>)}</section>
<section className="coral scene"><div className="coral-copy reveal"><p className="meta">10 · Coral Minute</p><h3>Then the sun<br/>changed everything.</h3></div><Photo src={photos[13]} alt="Warm sunrise portrait"/></section>
<section className="last scene"><Photo src={photos[5]} alt="Final wedding portrait"/><div className="last-copy reveal"><p className="meta">11 · Last Dry Frame</p><h3>A portrait before<br/>the water reached<br/>our footprints.</h3></div></section>
<section className="finale scene"><p className="meta">12 · The Shore Keeps Moving</p><div className="wordwave" aria-label="TIDEGLASS">{'TIDEGLASS'.split('').map((c,i)=><span key={i}>{c}</span>)}</div><p>Filed at first light. Returned by every tide.</p><button onClick={()=>scrollTo({top:0,behavior:'smooth'})}>Back to first light ↑</button></section></main>}
createRoot(document.getElementById('root')).render(<App/>);